version: "3"

services:
  app:
    build:
      context: ./.docker/app
    container_name: micro-videos-app
    image: isaquero/micro-videos-app:dev
    entrypoint: dockerize -template /templates/.env:.env -wait tcp://db:3306 -timeout 30s /entrypoint.sh
    volumes:
      - ./www:/var/www
    environment:
      - _DB_HOST=db
      - _DB_DATABASE=code_micro_videos
      - _DB_USERNAME=root
      - _DB_PASSWORD=root
    networks:
      - micro-videos-net
    depends_on:
      - db
      - redis

  nginx:
    build:
      context: ./.docker/nginx
    container_name: micro-videos-nginx
    image: isaquero/micro-videos-nginx:dev
    restart: always
    tty: true
    ports:
      - "8000:80"
    volumes:
      - ./www:/var/www
    networks:
      - micro-videos-net
    depends_on:
      - app

  db:
    build:
      context: ./.docker/mysql
    container_name: micro-videos-db
    image: isaquero/micro-videos-db:dev
    restart: always
    tty: true
    ports:
      - "33006:3306"
    volumes:
      - ./.docker/mysql/dbdata:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=code_micro_videos
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - micro-videos-net

  redis:
    image: redis:alpine
    container_name: micro-videos-redis
    expose:
      - 6379
    networks:
      - micro-videos-net

networks:
  micro-videos-net:
    driver: bridge
